spring:
  application:
    name: ims
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: MYSQL

  datasource:
    url: jdbc:mysql://localhost:3306/ims?serverTimezone=UTC
    username: root
    password:
    validation-query: SELECT 1

handlebars:
  suffix: .html
  cache: false
  expose-session-attributes: true
#  세션에 담긴 데이터를 모델에 담아 템플릿 엔진에 전달해주는 것